name: ddm_server
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  aqueduct: 3.3.0+1
  hive: ^1.4.4+1

dev_dependencies:
  aqueduct_test: ^1.0.0
  test: ^1.0.0
